"""Controlled-vocabulary aliases generated from the documented LLM API workflow.
Source artifact: docs/thesis_context/notebooks/llm_alias_service_generation_output_2026-06-29.json
"""
from __future__ import annotations

GENERATED_ENUM_VALUE_ALIASES: dict[str, dict[str, str]] = {
    'ActivityData.activity_type': {
        'distance traveled': 'distance_traveled',
        'distance travelled': 'distance_traveled',
        'mileage': 'distance_traveled',
        'travel distance': 'distance_traveled',
        'electric usage': 'electricity_consumption',
        'electricity consumption': 'electricity_consumption',
        'electricity use': 'electricity_consumption',
        'power consumption': 'electricity_consumption',
        'fuel burned': 'fuel_consumption',
        'fuel consumption': 'fuel_consumption',
        'fuel usage': 'fuel_consumption',
        'fuel use': 'fuel_consumption',
        'heat usage': 'heat_usage',
        'heat use': 'heat_usage',
        'heating usage': 'heat_usage',
        'thermal energy use': 'heat_usage',
        'material procurement': 'material_purchase',
        'material purchase': 'material_purchase',
        'materials purchased': 'material_purchase',
        'purchased material': 'material_purchase',
        'treated waste': 'waste_treatment',
        'waste disposal': 'waste_treatment',
        'waste processing': 'waste_treatment',
        'waste treatment': 'waste_treatment',
        'water consumed': 'water_usage',
        'water consumption': 'water_usage',
        'water usage': 'water_usage',
        'water use': 'water_usage',
    },
    'GHGEmissionRecord.scope': {
        'GHG scope 1': 'scope_1',
        'scope 1': 'scope_1',
        'scope one': 'scope_1',
        'GHG scope 2': 'scope_2',
        'scope 2': 'scope_2',
        'scope two': 'scope_2',
        'GHG scope 3': 'scope_3',
        'scope 3': 'scope_3',
        'scope three': 'scope_3',
    },
    'GHGEmissionRecord.scope3_category': {
        'business travel': 'business_travel',
        'company travel': 'business_travel',
        'corporate travel': 'business_travel',
        'work travel': 'business_travel',
        'capex goods': 'capital_goods',
        'capital assets': 'capital_goods',
        'capital equipment': 'capital_goods',
        'capital goods': 'capital_goods',
        'downstream leased assets': 'downstream_leased_assets',
        'downstream leases': 'downstream_leased_assets',
        'leased assets downstream': 'downstream_leased_assets',
        'downstream freight': 'downstream_transportation_and_distribution',
        'downstream logistics': 'downstream_transportation_and_distribution',
        'downstream transport and distribution': 'downstream_transportation_and_distribution',
        'downstream transportation and distribution': 'downstream_transportation_and_distribution',
        'commuting': 'employee_commuting',
        'employee commute': 'employee_commuting',
        'employee commuting': 'employee_commuting',
        'staff commuting': 'employee_commuting',
        'end of life disposal': 'end_of_life_treatment',
        'end of life treatment': 'end_of_life_treatment',
        'eol treatment': 'end_of_life_treatment',
        'franchise operations': 'franchises',
        'franchisees': 'franchises',
        'franchises': 'franchises',
        'energy related activities': 'fuel_and_energy_related_activities',
        'fuel and energy related activities': 'fuel_and_energy_related_activities',
        'fuel energy activities': 'fuel_and_energy_related_activities',
        'financed investments': 'investments',
        'investment emissions': 'investments',
        'investments': 'investments',
        'processing of sold products': 'processing_of_sold_products',
        'processing sold products': 'processing_of_sold_products',
        'sold product processing': 'processing_of_sold_products',
        'procured goods and services': 'purchased_goods_and_services',
        'purchased goods & services': 'purchased_goods_and_services',
        'purchased goods and services': 'purchased_goods_and_services',
        'purchases': 'purchased_goods_and_services',
        'leased assets upstream': 'upstream_leased_assets',
        'upstream leased assets': 'upstream_leased_assets',
        'upstream leases': 'upstream_leased_assets',
        'upstream freight': 'upstream_transportation_and_distribution',
        'upstream logistics': 'upstream_transportation_and_distribution',
        'upstream transport and distribution': 'upstream_transportation_and_distribution',
        'upstream transportation and distribution': 'upstream_transportation_and_distribution',
        'customer use of products': 'use_of_sold_products',
        'product use phase': 'use_of_sold_products',
        'sold product use': 'use_of_sold_products',
        'use of sold products': 'use_of_sold_products',
        'operational waste': 'waste_generated_in_operations',
        'operations waste': 'waste_generated_in_operations',
        'waste from operations': 'waste_generated_in_operations',
        'waste generated in operations': 'waste_generated_in_operations',
    },
}
