"""Field-label aliases generated from the documented LLM API workflow.
Source artifact: docs/thesis_context/notebooks/llm_alias_service_generation_output_2026-06-29.json
"""
from __future__ import annotations

ENTITY_LABEL_MAPPINGS: dict[tuple[str, str], dict[str, str]] = {
    ('emission', 'ActivityData'): {
        'activitycategory': 'ActivityData.activity_type',
        'activitycode': 'ActivityData.activity_type',
        'activityquantity': 'ActivityData.quantity',
        'activitytype': 'ActivityData.activity_type',
        'activityunit': 'ActivityData.unit',
        'amount': 'ActivityData.quantity',
        'consumedamount': 'ActivityData.quantity',
        'emissionactivity': 'ActivityData.activity_type',
        'inputquantity': 'ActivityData.quantity',
        'inputunit': 'ActivityData.unit',
        'quantityunit': 'ActivityData.unit',
        'usagequantity': 'ActivityData.quantity',
        'usageunit': 'ActivityData.unit',
    },
    ('emission', 'EmissionFactor'): {
        'co2factorunit': 'EmissionFactor.unit',
        'conversionfactor': 'EmissionFactor.value',
        'efunit': 'EmissionFactor.unit',
        'efvalue': 'EmissionFactor.value',
        'emissionfactor': 'EmissionFactor.value',
        'emissionfactorunit': 'EmissionFactor.unit',
        'emissionfactorvalue': 'EmissionFactor.value',
        'factorunit': 'EmissionFactor.unit',
        'factorvalue': 'EmissionFactor.value',
    },
    ('emission', 'GHGEmissionRecord'): {
        'calcmethod': 'GHGEmissionRecord.calculation_method',
        'calculatedemissions': 'GHGEmissionRecord.emissions_kg_co2e',
        'calculationmethod': 'GHGEmissionRecord.calculation_method',
        'category3': 'GHGEmissionRecord.scope3_category',
        'co2eemissions': 'GHGEmissionRecord.emissions_kg_co2e',
        'datasource': 'GHGEmissionRecord.provenance',
        'emissions': 'GHGEmissionRecord.emissions_kg_co2e',
        'emissionscope': 'GHGEmissionRecord.scope',
        'emissionsmethod': 'GHGEmissionRecord.calculation_method',
        'emissionssource': 'GHGEmissionRecord.provenance',
        'ghgscope': 'GHGEmissionRecord.scope',
        'ghgscope3category': 'GHGEmissionRecord.scope3_category',
        'methodused': 'GHGEmissionRecord.calculation_method',
        'protocolscope': 'GHGEmissionRecord.scope',
        'provenance': 'GHGEmissionRecord.provenance',
        'recordsource': 'GHGEmissionRecord.provenance',
        'reportedemissions': 'GHGEmissionRecord.emissions_kg_co2e',
        'scope3category': 'GHGEmissionRecord.scope3_category',
        'scopecategory': 'GHGEmissionRecord.scope',
        'sourcereference': 'GHGEmissionRecord.provenance',
        'totalemissions': 'GHGEmissionRecord.emissions_kg_co2e',
        'valuechaincategory': 'GHGEmissionRecord.scope3_category',
    },
    ('product', 'DPPInstance'): {
        'brewcount': 'DPPInstance.brewingCount',
        'brewingcount': 'DPPInstance.brewingCount',
        'brewingcycles': 'DPPInstance.brewingCount',
        'brewsmade': 'DPPInstance.brewingCount',
        'chalkcycles': 'DPPInstance.chalkCount',
        'cleancycles': 'DPPInstance.cleaningCount',
        'cleaningcount': 'DPPInstance.cleaningCount',
        'cleaningcycles': 'DPPInstance.cleaningCount',
        'coffeegrindingcount': 'DPPInstance.coffeeGrindingCount',
        'descalecount': 'DPPInstance.chalkCount',
        'descalingcount': 'DPPInstance.chalkCount',
        'descalingcycles': 'DPPInstance.chalkCount',
        'grindcycles': 'DPPInstance.coffeeGrindingCount',
        'grindercycles': 'DPPInstance.coffeeGrindingCount',
        'grindingcount': 'DPPInstance.coffeeGrindingCount',
        'hoursoperated': 'DPPInstance.operatingHRS',
        'machinehours': 'DPPInstance.operatingHRS',
        'numberofbrews': 'DPPInstance.brewingCount',
        'numberofcleans': 'DPPInstance.cleaningCount',
        'numberofgrinds': 'DPPInstance.coffeeGrindingCount',
        'operatinghours': 'DPPInstance.operatingHRS',
        'runtimehours': 'DPPInstance.operatingHRS',
        'scaleremovalcount': 'DPPInstance.chalkCount',
        'usagehours': 'DPPInstance.operatingHRS',
    },
    ('product', 'DPPStatic'): {
        'deviceclass': 'DPPStatic.productClass',
        'machineclass': 'DPPStatic.productClass',
        'machinedepth': 'DPPStatic.depthCM',
        'machineheight': 'DPPStatic.heightCM',
        'machinename': 'DPPStatic.name',
        'machineweight': 'DPPStatic.weightGRM',
        'machinewidth': 'DPPStatic.widthCM',
        'modeldepth': 'DPPStatic.depthCM',
        'modelheight': 'DPPStatic.heightCM',
        'modelname': 'DPPStatic.name',
        'modelweight': 'DPPStatic.weightGRM',
        'modelwidth': 'DPPStatic.widthCM',
        'overalldepth': 'DPPStatic.depthCM',
        'overallheight': 'DPPStatic.heightCM',
        'overallweight': 'DPPStatic.weightGRM',
        'overallwidth': 'DPPStatic.widthCM',
        'productcategory': 'DPPStatic.productClass',
        'productclass': 'DPPStatic.productClass',
        'productdepth': 'DPPStatic.depthCM',
        'productheight': 'DPPStatic.heightCM',
        'productmodel': 'DPPStatic.name',
        'productname': 'DPPStatic.name',
        'productweight': 'DPPStatic.weightGRM',
        'productwidth': 'DPPStatic.widthCM',
    },
    ('product', 'MaterialInstance'): {
        'componentmaterialweight': 'MaterialInstance.weightGRM',
        'instanceweight': 'MaterialInstance.weightGRM',
        'materialmass': 'MaterialInstance.weightGRM',
        'materialpurity': 'MaterialInstance.purityLevel',
        'materialpuritylevel': 'MaterialInstance.purityLevel',
        'materialweight': 'MaterialInstance.weightGRM',
        'percentrecycled': 'MaterialInstance.percentRecycled',
        'puritylevel': 'MaterialInstance.purityLevel',
        'purityratio': 'MaterialInstance.purityLevel',
        'recycledcontent': 'MaterialInstance.percentRecycled',
        'recycledmaterialpercent': 'MaterialInstance.percentRecycled',
        'recycledpercentage': 'MaterialInstance.percentRecycled',
        'recycledshare': 'MaterialInstance.percentRecycled',
    },
    ('product', 'PartInstance'): {
        'failstate': 'PartInstance.hasFailstate',
        'failurestateflag': 'PartInstance.hasFailstate',
        'hasfailstate': 'PartInstance.hasFailstate',
        'hasfailure': 'PartInstance.hasFailstate',
        'ismodular': 'PartInstance.isModular',
        'modularityflag': 'PartInstance.isModular',
        'modularpart': 'PartInstance.isModular',
        'partfailed': 'PartInstance.hasFailstate',
        'partmodular': 'PartInstance.isModular',
    },
    ('product', 'PartStatic'): {
        'componentdepth': 'PartStatic.depthCM',
        'componentheight': 'PartStatic.heightCM',
        'componentweight': 'PartStatic.weightGRM',
        'componentwidth': 'PartStatic.widthCM',
        'partdepth': 'PartStatic.depthCM',
        'partheight': 'PartStatic.heightCM',
        'partmass': 'PartStatic.weightGRM',
        'partweight': 'PartStatic.weightGRM',
        'partwidth': 'PartStatic.widthCM',
        'staticpartdepth': 'PartStatic.depthCM',
        'staticpartheight': 'PartStatic.heightCM',
        'staticpartweight': 'PartStatic.weightGRM',
        'staticpartwidth': 'PartStatic.widthCM',
    },
    ('service', 'CleaningServiceStep'): {
        'cleanedpart': 'CleaningServiceStep.cleanedPartId',
        'cleanedpartid': 'CleaningServiceStep.cleanedPartId',
        'cleaningcost': 'CleaningServiceStep.costEur',
        'cleantargetpart': 'CleaningServiceStep.cleanedPartId',
        'costineuros': 'CleaningServiceStep.costEur',
        'customersymptoms': 'CleaningServiceStep.observedSymptoms',
        'diagnosetext': 'CleaningServiceStep.diagnose',
        'diagnosis': 'CleaningServiceStep.diagnose',
        'diagnosticnotes': 'CleaningServiceStep.diagnose',
        'faultdiagnosis': 'CleaningServiceStep.diagnose',
        'observedsymptoms': 'CleaningServiceStep.observedSymptoms',
        'partcleaned': 'CleaningServiceStep.cleanedPartId',
        'reportedsymptoms': 'CleaningServiceStep.observedSymptoms',
        'servicecost': 'CleaningServiceStep.costEur',
        'servicediagnosis': 'CleaningServiceStep.diagnose',
        'stepcost': 'CleaningServiceStep.costEur',
        'symptomnotes': 'CleaningServiceStep.observedSymptoms',
        'symptoms': 'CleaningServiceStep.observedSymptoms',
    },
    ('service', 'RefurbishmentServiceStep'): {
        'cleanedpartids': 'RefurbishmentServiceStep.cleanedPartIds',
        'cleanedparts': 'RefurbishmentServiceStep.cleanedPartIds',
        'cleantargetparts': 'RefurbishmentServiceStep.cleanedPartIds',
        'costineuros': 'RefurbishmentServiceStep.costEur',
        'customersymptoms': 'RefurbishmentServiceStep.observedSymptoms',
        'diagnosetext': 'RefurbishmentServiceStep.diagnose',
        'diagnosis': 'RefurbishmentServiceStep.diagnose',
        'diagnosticnotes': 'RefurbishmentServiceStep.diagnose',
        'faultdiagnosis': 'RefurbishmentServiceStep.diagnose',
        'observedsymptoms': 'RefurbishmentServiceStep.observedSymptoms',
        'partscleaned': 'RefurbishmentServiceStep.cleanedPartIds',
        'partsrepaired': 'RefurbishmentServiceStep.repairedPartIds',
        'refurbdiagnosis': 'RefurbishmentServiceStep.diagnose',
        'refurbishmentcost': 'RefurbishmentServiceStep.costEur',
        'repairedpartids': 'RefurbishmentServiceStep.repairedPartIds',
        'repairedparts': 'RefurbishmentServiceStep.repairedPartIds',
        'repairtargetparts': 'RefurbishmentServiceStep.repairedPartIds',
        'reportedsymptoms': 'RefurbishmentServiceStep.observedSymptoms',
        'servicecost': 'RefurbishmentServiceStep.costEur',
        'stepcost': 'RefurbishmentServiceStep.costEur',
        'symptomnotes': 'RefurbishmentServiceStep.observedSymptoms',
        'symptoms': 'RefurbishmentServiceStep.observedSymptoms',
    },
    ('service', 'RemanufacturingServiceStep'): {
        'cleanedpartids': 'RemanufacturingServiceStep.cleanedPartIds',
        'cleanedparts': 'RemanufacturingServiceStep.cleanedPartIds',
        'cleantargetparts': 'RemanufacturingServiceStep.cleanedPartIds',
        'costineuros': 'RemanufacturingServiceStep.costEur',
        'customersymptoms': 'RemanufacturingServiceStep.observedSymptoms',
        'diagnosetext': 'RemanufacturingServiceStep.diagnose',
        'diagnosis': 'RemanufacturingServiceStep.diagnose',
        'diagnosticnotes': 'RemanufacturingServiceStep.diagnose',
        'faultdiagnosis': 'RemanufacturingServiceStep.diagnose',
        'observedsymptoms': 'RemanufacturingServiceStep.observedSymptoms',
        'partscleaned': 'RemanufacturingServiceStep.cleanedPartIds',
        'partsrepaired': 'RemanufacturingServiceStep.repairedPartIds',
        'remanufacturingcost': 'RemanufacturingServiceStep.costEur',
        'remanufacturingdiagnosis': 'RemanufacturingServiceStep.diagnose',
        'repairedpartids': 'RemanufacturingServiceStep.repairedPartIds',
        'repairedparts': 'RemanufacturingServiceStep.repairedPartIds',
        'repairtargetparts': 'RemanufacturingServiceStep.repairedPartIds',
        'reportedsymptoms': 'RemanufacturingServiceStep.observedSymptoms',
        'servicecost': 'RemanufacturingServiceStep.costEur',
        'stepcost': 'RemanufacturingServiceStep.costEur',
        'symptomnotes': 'RemanufacturingServiceStep.observedSymptoms',
        'symptoms': 'RemanufacturingServiceStep.observedSymptoms',
    },
    ('service', 'RepairServiceStep'): {
        'costineuros': 'RepairServiceStep.costEur',
        'customersymptoms': 'RepairServiceStep.observedSymptoms',
        'diagnosetext': 'RepairServiceStep.diagnose',
        'diagnosis': 'RepairServiceStep.diagnose',
        'diagnosticnotes': 'RepairServiceStep.diagnose',
        'faultdiagnosis': 'RepairServiceStep.diagnose',
        'observedsymptoms': 'RepairServiceStep.observedSymptoms',
        'partrepaired': 'RepairServiceStep.repairedPartId',
        'repaircost': 'RepairServiceStep.costEur',
        'repairdiagnosis': 'RepairServiceStep.diagnose',
        'repairedpart': 'RepairServiceStep.repairedPartId',
        'repairedpartid': 'RepairServiceStep.repairedPartId',
        'repairtargetpart': 'RepairServiceStep.repairedPartId',
        'reportedsymptoms': 'RepairServiceStep.observedSymptoms',
        'servicecost': 'RepairServiceStep.costEur',
        'stepcost': 'RepairServiceStep.costEur',
        'symptomnotes': 'RepairServiceStep.observedSymptoms',
        'symptoms': 'RepairServiceStep.observedSymptoms',
    },
    ('service', 'ReplaceServiceStep'): {
        'costineuros': 'ReplaceServiceStep.costEur',
        'customersymptoms': 'ReplaceServiceStep.observedSymptoms',
        'diagnosetext': 'ReplaceServiceStep.diagnose',
        'diagnosis': 'ReplaceServiceStep.diagnose',
        'diagnosticnotes': 'ReplaceServiceStep.diagnose',
        'faultdiagnosis': 'ReplaceServiceStep.diagnose',
        'observedsymptoms': 'ReplaceServiceStep.observedSymptoms',
        'partreplaced': 'ReplaceServiceStep.replacedPartId',
        'replacedpart': 'ReplaceServiceStep.replacedPartId',
        'replacedpartid': 'ReplaceServiceStep.replacedPartId',
        'replacementcost': 'ReplaceServiceStep.costEur',
        'replacementdiagnosis': 'ReplaceServiceStep.diagnose',
        'replacementtargetpart': 'ReplaceServiceStep.replacedPartId',
        'reportedsymptoms': 'ReplaceServiceStep.observedSymptoms',
        'servicecost': 'ReplaceServiceStep.costEur',
        'stepcost': 'ReplaceServiceStep.costEur',
        'symptomnotes': 'ReplaceServiceStep.observedSymptoms',
        'symptoms': 'ReplaceServiceStep.observedSymptoms',
    },
    ('service', 'SecondaryValueStep'): {
        'costineuros': 'SecondaryValueStep.costEur',
        'customersymptoms': 'SecondaryValueStep.observedSymptoms',
        'diagnosetext': 'SecondaryValueStep.diagnose',
        'diagnosis': 'SecondaryValueStep.diagnose',
        'diagnosticnotes': 'SecondaryValueStep.diagnose',
        'faultdiagnosis': 'SecondaryValueStep.diagnose',
        'observedsymptoms': 'SecondaryValueStep.observedSymptoms',
        'reportedsymptoms': 'SecondaryValueStep.observedSymptoms',
        'secondaryvaluecost': 'SecondaryValueStep.costEur',
        'secondaryvaluediagnosis': 'SecondaryValueStep.diagnose',
        'servicecost': 'SecondaryValueStep.costEur',
        'stepcost': 'SecondaryValueStep.costEur',
        'symptomnotes': 'SecondaryValueStep.observedSymptoms',
        'symptoms': 'SecondaryValueStep.observedSymptoms',
    },
}
