"""
Output builders for harmonization results.

The harmonization service keeps a detailed intermediate representation for
traceability. This module derives two user-facing outputs from it:

1. Clean JSON-LD data: only canonical entity fields and trusted references.
2. Harmonization report: mapping/normalization metadata, confidence values,
   unmapped fields, and issues.
"""

from __future__ import annotations

from dataclasses import asdict
from typing import Any

from dpp.data_quality.harmonization.schemas import HarmonizationResult, HarmonizedEntity


def _context_from_document(document: dict[str, Any]) -> Any:
    """Return the input JSON-LD context, or a minimal fallback context."""
    return document.get("@context", {"dpp": "https://example.org/dpp#"})


def _field_name_from_path(canonical_path: str) -> str:
    """Return the field name from a canonical path such as 'ActivityData.quantity'."""
    return canonical_path.split(".", maxsplit=1)[1]


def _clean_value(field_dict: dict[str, Any]) -> Any:
    """Return the value that should appear in clean canonical data."""
    normalized_value = field_dict.get("normalized_value")
    if normalized_value is not None:
        return normalized_value

    return field_dict.get("original_value")


def _drop_none_values(value: Any) -> Any:
    """Recursively remove keys whose value is None from report dictionaries."""
    if isinstance(value, dict):
        return {
            key: _drop_none_values(item)
            for key, item in value.items()
            if item is not None
        }

    if isinstance(value, list):
        return [_drop_none_values(item) for item in value]

    return value


def _as_measurement_value(raw_value: Any, unit: str | None) -> dict[str, Any] | None:
    """Return a consistent value/unit object for report output."""
    if unit is None:
        return None

    if isinstance(raw_value, dict) and "value" in raw_value:
        value = raw_value.get("value")
    else:
        value = raw_value

    return {"value": value, "unit": unit}


def _format_measurement_field_for_report(field_dict: dict[str, Any]) -> dict[str, Any]:
    """
    Represent measurement normalization symmetrically in reports.

    Internally, HarmonizedField stores units as separate trace metadata
    (original_unit / normalized_unit). In the user-facing report, value and unit
    belong together. Therefore a field such as productWeight is rendered as:

        original_value:   {value: 2.5, unit: kg}
        normalized_value: {value: 2500.0, unit: g}

    Fields without unit metadata, including explicit unit fields such as
    ActivityData.unit, are left untouched.
    """
    original_unit = field_dict.get("original_unit")
    normalized_unit = field_dict.get("normalized_unit")

    if original_unit is None and normalized_unit is None:
        return field_dict

    formatted = dict(field_dict)

    original_measurement = _as_measurement_value(
        raw_value=formatted.get("original_value"),
        unit=original_unit,
    )
    if original_measurement is not None:
        formatted["original_value"] = original_measurement

    if formatted.get("normalized_value") is not None and normalized_unit is not None:
        formatted["normalized_value"] = {
            "value": formatted["normalized_value"],
            "unit": normalized_unit,
        }

    formatted.pop("original_unit", None)
    formatted.pop("normalized_unit", None)
    return formatted




def _is_normalized_free_text_path(canonical_path: str) -> bool:
    """Return True for companion fields generated by free-text harmonization."""
    return canonical_path.endswith(".normalizedDiagnose") or canonical_path.endswith(".normalizedObservedSymptoms")


def _is_free_text_source_path(canonical_path: str) -> bool:
    """Return True for original service-text source fields."""
    return canonical_path.endswith(".diagnose") or canonical_path.endswith(".observedSymptoms")


def _format_service_field_for_report(canonical_path: str, field_dict: dict[str, Any]) -> dict[str, Any]:
    """Return a compact report entry for service-scope fields.

    Service fields are already typed by the prototype model. For fields such as
    costEur, the harmonization layer only recognizes the canonical field and
    preserves the value. Therefore label-confidence metadata would be noisy here.
    Detailed concept matching remains available in the separate text_harmonization
    section for diagnose and observedSymptoms.
    """
    compact: dict[str, Any] = {
        "canonical_path": field_dict.get("canonical_path"),
        "original_value": field_dict.get("original_value"),
        "status": field_dict.get("status"),
    }

    original_label = field_dict.get("original_label")
    canonical_field_name = canonical_path.rsplit(".", maxsplit=1)[1]
    if original_label is not None and original_label != canonical_field_name:
        compact["input_label"] = original_label

    normalized_value = field_dict.get("normalized_value")
    original_value = field_dict.get("original_value")
    if (
        normalized_value is not None
        and normalized_value != original_value
        and not _is_free_text_source_path(canonical_path)
    ):
        compact["normalized_value"] = normalized_value

    return compact

def _add_preserved_references(node: dict[str, Any], entity: HarmonizedEntity) -> None:
    """
    Add trusted graph references as normal JSON-LD properties.

    Relations are not emitted as a separate top-level 'relations' category in
    clean output. They become ordinary reference fields on the source entity.
    """
    grouped_references: dict[str, list[dict[str, str]]] = {}

    for relation in entity.relations:
        grouped_references.setdefault(relation.relation_name, []).append(
            {"@id": relation.target_entity_id}
        )

    for relation_name, references in grouped_references.items():
        if len(references) == 1:
            node[relation_name] = references[0]
        else:
            node[relation_name] = references


def build_clean_jsonld(result: HarmonizationResult, document: dict[str, Any] | None = None) -> dict[str, Any]:
    """
    Build clean canonical JSON-LD from a harmonization result.

    The output intentionally excludes original labels, original values,
    confidence scores, status flags, warnings, and issues. It is meant to be the
    normalized data payload for downstream processing.
    """
    graph: list[dict[str, Any]] = []

    for entity in result.entities.values():
        node: dict[str, Any] = {
            "@id": entity.entity_id,
            "@type": entity.entity_type,
        }

        for canonical_path, harmonized_field in entity.fields.items():
            if harmonized_field.status in {"error", "ambiguous", "unmapped"}:
                continue

            field_name = _field_name_from_path(canonical_path)
            node[field_name] = _clean_value(asdict(harmonized_field))

        _add_preserved_references(node, entity)
        graph.append(node)

    return {
        "@context": _context_from_document(document or {}),
        "@graph": graph,
    }



def _iter_text_harmonization_entries(value: Any) -> list[dict[str, Any]]:
    """Return flat free-text harmonization entries from an entity report section."""
    entries: list[dict[str, Any]] = []

    if isinstance(value, dict):
        if "status" in value and "original_value" in value:
            entries.append(value)
        else:
            for item in value.values():
                entries.extend(_iter_text_harmonization_entries(item))
        return entries

    if isinstance(value, list):
        for item in value:
            entries.extend(_iter_text_harmonization_entries(item))

    return entries


def _build_report_summary(result: HarmonizationResult, report_entities: dict[str, Any]) -> dict[str, Any]:
    """Build compact counts for global and entity-level report content.

    The detailed issue lists stay in their original locations. This summary only
    makes it visible at report level that entity-level infos/warnings/errors exist,
    even when there are no global pipeline issues.
    """
    entity_issues = [
        issue
        for entity in result.entities.values()
        for issue in entity.issues
    ]
    all_issues = [*result.issues, *entity_issues]

    field_status_counts: dict[str, int] = {}
    for entity in result.entities.values():
        for field in entity.fields.values():
            field_status_counts[field.status] = field_status_counts.get(field.status, 0) + 1

    text_status_counts: dict[str, int] = {}
    for entity_dict in report_entities.values():
        for entry in _iter_text_harmonization_entries(entity_dict.get("text_harmonization", {})):
            status = entry.get("status")
            if isinstance(status, str):
                text_status_counts[status] = text_status_counts.get(status, 0) + 1

    severity_counts = {
        "info": sum(1 for issue in all_issues if issue.severity == "info"),
        "warning": sum(1 for issue in all_issues if issue.severity == "warning"),
        "error": sum(1 for issue in all_issues if issue.severity == "error"),
    }

    return {
        "entities_total": len(result.entities),
        "fields_total": sum(len(entity.fields) for entity in result.entities.values()),
        "unmapped_fields_total": sum(len(entity.unmapped_fields) for entity in result.entities.values()),
        "field_status_counts": field_status_counts,
        "text_harmonization_status_counts": text_status_counts,
        "issues_total": len(all_issues),
        "global_issues_total": len(result.issues),
        "entity_issues_total": len(entity_issues),
        "issue_severity_counts": severity_counts,
        "has_errors": result.has_errors(),
    }

def build_harmonization_report(result: HarmonizationResult) -> dict[str, Any]:
    """
    Build a traceability report from a harmonization result.

    Trusted structural references are intentionally omitted from the report,
    because they are not harmonized by this layer. They appear as normal JSON-LD
    reference properties in the clean data output.
    """
    report_entities: dict[str, Any] = {}

    for entity_id, entity in result.entities.items():
        entity_dict = asdict(entity)
        entity_dict.pop("relations", None)

        if result.scope_name == "service":
            entity_dict["fields"] = {
                canonical_path: _format_service_field_for_report(canonical_path, field_dict)
                for canonical_path, field_dict in entity_dict.get("fields", {}).items()
                if not _is_normalized_free_text_path(canonical_path)
            }
        else:
            entity_dict["fields"] = {
                canonical_path: _format_measurement_field_for_report(field_dict)
                for canonical_path, field_dict in entity_dict.get("fields", {}).items()
            }

        if not entity_dict.get("text_harmonization"):
            entity_dict.pop("text_harmonization", None)

        report_entities[entity_id] = _drop_none_values(entity_dict)

    return {
        "scope_name": result.scope_name,
        "summary": _build_report_summary(result, report_entities),
        "entities": report_entities,
        "issues": [_drop_none_values(asdict(issue)) for issue in result.issues],
    }


def build_full_output(result: HarmonizationResult, document: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build the combined data/report wrapper used by the CLI default output."""
    return {
        "data": build_clean_jsonld(result, document=document),
        "report": build_harmonization_report(result),
        "has_errors": result.has_errors(),
    }
