"""
OpenRepairData-derived service concept registry for free-text harmonization.

This module contains the canonical diagnosis and symptom concepts used by the
service free-text harmonizer. Concept descriptions, validated registry surface
forms, and soft context metadata are generated from the documented LLM API
workflow in docs/thesis_context/notebooks/llm_alias_and_service_description_generation_2026-06-29.ipynb
using the 2026-07-10 input, prompt, and output artifacts. Trace evidence
phrases remain in the notebook artifacts and are only accepted as registry
surface forms after validation.

Matching logic stays in free_text.py, so the registry can be reviewed and
extended without changing the normalization algorithm.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


TextConceptKind = Literal["symptom", "diagnosis"]
TextConceptInventoryStatus = Literal["core", "review_candidate"]


@dataclass(frozen=True)
class TextConcept:
    """
    Canonical free-text concept used for service-text harmonization.

    Attributes:
        concept_id: Stable machine-readable identifier.
        label: Human-readable canonical label.
        kind: Concept registry kind, e.g. symptom or diagnosis.
        description: Short semantic description used for embedding matching.
        examples: Validated registry surface forms used by exact, fuzzy, and embedding matching.
        applicable_service_types: Optional service-step types where the concept is especially plausible.
        related_part_keywords: Optional part-name keywords kept as soft context metadata.
        inventory_status: Whether the concept is part of the OpenRepairData-derived core vocabulary or a review candidate.
    """

    concept_id: str
    label: str
    kind: TextConceptKind
    description: str
    examples: tuple[str, ...] = ()
    applicable_service_types: tuple[str, ...] = ()
    related_part_keywords: tuple[str, ...] = ()
    inventory_status: TextConceptInventoryStatus = "core"


SYMPTOM_CONCEPTS: tuple[TextConcept, ...] = (
    TextConcept(
        concept_id='does_not_turn_on',
        label='Does not turn on',
        kind='symptom',
        description='Machine does not start, switch on, or turn on when the user attempts to power it.',
        examples=(
            "won't turn on",
            'does not switch on',
            'not turning on',
            "can't start",
            "didn't turn on",
            'Shorts out the power',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'power switch',
            'power button',
            'plug',
            'fuse',
            'power supply',
            'control panel',
        ),
    ),
    TextConcept(
        concept_id='generic_not_working',
        label='Generic not working',
        kind='symptom',
        description='Underspecified report that the coffee machine or maker does not work, without a clearer symptom.',
        examples=(
            'coffee machine not working',
            'coffee maker not working',
            "coffee maker doesn't work",
            "machine doesn't work",
            'nothing happens',
            'nothing happens when its turned on',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'coffee machine',
            'coffee maker',
            'machine',
            'appliance',
        ),
    ),
    TextConcept(
        concept_id='grinder_not_working',
        label='Grinder not working',
        kind='symptom',
        description='Coffee grinder does not grind, has stopped grinding, or will not grind coffee beans.',
        examples=(
            'coffee grinder not grinding',
            'grinder not working',
            'will not grind',
            "won't grind coffee",
            'stopped grinding coffee',
            "won't grind",
            'coffee grinder not working',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'grinder',
            'coffee grinder',
            'grinding motor',
            'burrs',
            'beans',
            'grind mechanism',
        ),
    ),
    TextConcept(
        concept_id='no_coffee_output',
        label='No coffee output',
        kind='symptom',
        description='Machine fails to brew or dispense coffee, while the exact water-flow cause is not specified.',
        examples=(
            'no coffee coming out',
            'coffee not coming out',
            'did not brew',
            'will not brew coffee',
            'no coffee output',
            'not brewing coffee',
            'Not frothing milk but makes coffee okay',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'brew outlet',
            'coffee outlet',
            'brew unit',
            'pod holder',
            'water path',
        ),
    ),
    TextConcept(
        concept_id='no_power_or_no_lights',
        label='No power or no lights',
        kind='symptom',
        description='No electrical power, display, or indicator lights are visible on the coffee machine.',
        examples=(
            'no power',
            'no electrical power',
            'no power to display',
            'no lights on panel',
            'light not coming on',
            'no light',
            'No power to the display',
            'No lights on operation panel',
            'no power getting through to the mechanism',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'power supply',
            'plug',
            'fuse',
            'display',
            'operation panel',
            'indicator light',
        ),
    ),
    TextConcept(
        concept_id='no_water_flow',
        label='No water flow',
        kind='symptom',
        description='Water or coffee does not come through the brewing path to make coffee.',
        examples=(
            'no water coming through',
            'water not going through',
            'water not getting through',
            'coffee not coming through',
            'no water coming out to make coffee',
            'not percolating',
            'water not getting through to the coffee',
            'Will not pour coffee',
            'water not coming through',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'water path',
            'brew unit',
            'pump',
            'tubing',
            'coffee outlet',
            'filter',
        ),
    ),
    TextConcept(
        concept_id='not_pumping_water',
        label='Not pumping water',
        kind='symptom',
        description='Pump appears not to move water, or water is not being pumped through the system.',
        examples=(
            'not pumping water',
            'water not pumping',
            "won't pump water",
            'water not moving',
            'pump not moving water',
            'water not coming as normal',
            "Water's not moving",
            'Water will not go through',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pump',
            'water pump',
            'water line',
            'reservoir',
            'tubing',
        ),
    ),
    TextConcept(
        concept_id='pod_jam_or_lid_not_closing',
        label='Pod jam or lid not closing',
        kind='symptom',
        description='Pod or capsule is jammed, stuck, or prevents lid/pod cavity closure.',
        examples=(
            'pod jam',
            'jammed pods',
            'stuck coffee pod',
            "lid won't close",
            'pod cavity not closing',
            'pod jams',
            'Two jammed pods inside',
            'Not closing pod cavity',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pod',
            'capsule',
            'pod cavity',
            'lid',
            'pod holder',
            'handle',
        ),
    ),
    TextConcept(
        concept_id='pod_not_pierced',
        label='Pod not pierced',
        kind='symptom',
        description='Machine does not pierce or punch holes in coffee pods or capsules properly.',
        examples=(
            'pods not pierced',
            'pod not piercing',
            'machine does not pierce pods',
            'not piercing coffee capsules',
            'stopped punching holes in pods',
            'does not pierce the pod',
            'Stopped punching holes in the pods',
            'Pods were not pierced properly',
            'coffee pods not being pierced',
            'Not piercing pods',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pod',
            'capsule',
            'piercer',
            'needle',
            'plunger',
            'pod mechanism',
        ),
    ),
    TextConcept(
        concept_id='power_on_but_no_operation',
        label='Power on but no operation',
        kind='symptom',
        description='Machine powers up or lights come on, but no brewing or mechanical operation follows.',
        examples=(
            'power on but nothing happens',
            'powers up but nothing happens',
            'light comes on but nothing happens',
            'power is on but no operation',
            'powers up but not working',
            'Light comes on when plugged in , but nothing happens',
            'Power is on - but nothing happening',
            'Powers up but something wrong',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'power light',
            'control panel',
            'main board',
            'pump',
            'brew mechanism',
        ),
    ),
    TextConcept(
        concept_id='reduced_water_flow_or_low_pressure',
        label='Reduced water flow or low pressure',
        kind='symptom',
        description='Water flow is weak, slow, insufficient, or under low pressure through the coffee machine.',
        examples=(
            'low water pressure',
            'low water flow',
            'not dispensing enough water',
            'pumps slowly',
            'no pressure through system',
            'reduced water flow',
            'blockage',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pump',
            'water path',
            'tubing',
            'nozzle',
            'filter',
            'scale',
            'blockage',
        ),
    ),
    TextConcept(
        concept_id='steam_leak',
        label='Steam leak',
        kind='symptom',
        description='Steam, sometimes with water, leaks from the steam control or steam wand area.',
        examples=(
            'steam leaking from control',
            'steam wand leaking',
            'steam leak',
            'leaking steam',
            'steam and water leaking',
            'steam leak from wand',
            'some water and steam out but nothing more',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'steam wand',
            'steam control',
            'steam valve',
            'seal',
            'wand connector',
        ),
    ),
    TextConcept(
        concept_id='steam_wand_not_working',
        label='Steam wand not working',
        kind='symptom',
        description='Steam wand or steamer function has low power, functions poorly, or does not work.',
        examples=(
            'steam wand not working',
            'steamer not working',
            'steam wand losing power',
            'steamer wand not functioning',
            'not steaming properly',
            'steam function not working',
            'Steamer wand no longer fundtions',
            'Not steam properly',
            'further repair required to address steamer',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'steam wand',
            'steamer',
            'steam nozzle',
            'steam valve',
            'frother',
        ),
    ),
    TextConcept(
        concept_id='water_leakage',
        label='Water leakage',
        kind='symptom',
        description='Water leaks from the coffee machine during operation or from an unspecified internal/base location.',
        examples=(
            'water leak',
            'leaking water',
            'machine leaking water',
            'water leaking from machine',
            'leaking inside',
            'leaking from base',
            'Leaking water when operational',
            'Machine leaking',
            'Water leaking from the machine',
            'leaking from the base',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'seal',
            'gasket',
            'base',
            'reservoir',
            'water tank',
            'hose',
            'tubing',
        ),
    ),
    TextConcept(
        concept_id='water_not_heating',
        label='Water not heating',
        kind='symptom',
        description='Water does not heat up, or the boiler fails to heat water for brewing.',
        examples=(
            'water not heating',
            'not heating water',
            'water not heating up',
            "won't heat water",
            "boiler doesn't heat water",
            "doesn't heat up",
            "water don't heat",
            "boiler doesn't heat the water",
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'heating element',
            'boiler',
            'heater',
            'thermostat',
            'thermal fuse',
        ),
    ),
    TextConcept(
        concept_id='grinder_not_switching_on',
        label='Grinder not switching on',
        kind='symptom',
        description='Coffee grinder specifically does not switch on or start, distinct from general machine power failure.',
        examples=(
            'grinder not switching on',
            'coffee grinder not switching on',
            "grinder doesn't turn on",
            "coffee grinder doesn't turn on",
            'grinder will not start',
            'not switching on',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'grinder',
            'coffee grinder',
            'grinder motor',
            'grind switch',
            'beans',
        ),
        inventory_status='review_candidate',
    ),
    TextConcept(
        concept_id='indicator_light_error',
        label='Indicator light error',
        kind='symptom',
        description='Indicator light shows an error state, such as red or flashing light, or fails to change to green.',
        examples=(
            'red light error',
            'red light flashing',
            'indicator light error',
            "red light won't change to green",
            'red instead of green light',
            'flashing red light',
            'Red light still comes on',
            'flashing light. red light flashing',
            'red light comes on rather than the green one',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'indicator light',
            'red light',
            'green light',
            'display',
            'control panel',
            'status light',
        ),
        inventory_status='review_candidate',
    ),
    TextConcept(
        concept_id='pod_area_leakage',
        label='Pod area leakage',
        kind='symptom',
        description='Water leakage is located at or near the pod/capsule insertion area or pod cavity.',
        examples=(
            'leaks water from pod area',
            'pod area water leak',
            'leak from pod cavity',
            'leak where pods are inserted',
            'capsule area leaking',
            'water leaking from pod holder',
            'Leaks water from pod',
            'leak is coming from the area where the pods are inserted',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pod',
            'capsule',
            'pod cavity',
            'pod holder',
            'capsule holder',
            'lid seal',
        ),
        inventory_status='review_candidate',
    ),
)


DIAGNOSIS_CONCEPTS: tuple[TextConcept, ...] = (
    TextConcept(
        concept_id='air_in_pump_or_pipe',
        label='Air in pump or pipe',
        kind='diagnosis',
        description='Air trapped in the pump or connected pipework causing water-flow or pumping problems.',
        examples=(
            'air in pump',
            'air in water pump',
            'air in pump pipe',
            'air trapped in pump line',
            'airlock in pump or pipe',
            'Pump had air in the pipe',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pump',
            'water pump',
            'pipe',
            'tubing',
            'hose',
            'water line',
        ),
    ),
    TextConcept(
        concept_id='blocked_or_disconnected_flow_path',
        label='Blocked or disconnected flow path',
        kind='diagnosis',
        description='Water-flow path is blocked, plugged, or disconnected between tubing, pump, and related connectors.',
        examples=(
            'blocked flow path',
            'blocked tubing',
            'plugged tubing',
            'disconnected water line',
            'pump connection came off',
            'water line blocked',
            'or is blocked',
            'Connection to water pump had come off',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'tubing',
            'hose',
            'pipe',
            'connector',
            'water line',
            'pump connection',
            'flow path',
        ),
    ),
    TextConcept(
        concept_id='blocked_steam_nozzle',
        label='Blocked steam nozzle',
        kind='diagnosis',
        description='Steam nozzle or steamer outlet is blocked and requires cleaning or unblocking.',
        examples=(
            'blocked steam nozzle',
            'blocked steamer nozzle',
            'steam nozzle clogged',
            'steamer nozzle clogged',
            'nozzle unblocked',
            'Blocked Nozzle',
            'cleaned steamer nozzle',
            'Cleaned and unblocked the nozzle',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'steam nozzle',
            'steamer nozzle',
            'nozzle',
            'steam wand',
            'outlet',
        ),
    ),
    TextConcept(
        concept_id='dirty_or_corroded_contacts',
        label='Dirty or corroded contacts',
        kind='diagnosis',
        description='Electrical switch or button contacts are dirty, worn, carbonized, or corroded.',
        examples=(
            'dirty switch contacts',
            'corroded switch contacts',
            'dirty button contacts',
            'worn button contact',
            'carbon on contacts',
            'steam damaged contacts',
            'button contact worn off',
            'Switch dirty contacts',
            'switch corroded',
            'dirty on/off button',
            'carbon or steam',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'switch',
            'button',
            'contacts',
            'on/off button',
            'tact switch',
            'control panel',
        ),
    ),
    TextConcept(
        concept_id='fuse_or_thermal_fuse_fault',
        label='Fuse or thermal fuse fault',
        kind='diagnosis',
        description='Plug fuse, internal fuse, or thermal fuse is blown, faulty, or needs replacement.',
        examples=(
            'blown fuse',
            'plug fuse blown',
            'thermal fuse blown',
            'thermal fuse fault',
            'fuse fault',
            'needs thermal fuse',
            'Thermal fuse',
            'Fault identified as likely to be the fuse',
            'Need thermal fuse',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'fuse',
            'plug fuse',
            'thermal fuse',
            'thermal cutout',
            'power circuit',
        ),
    ),
    TextConcept(
        concept_id='heating_element_failure',
        label='Heating element failure',
        kind='diagnosis',
        description='Heating element has failed electrically or is not receiving power.',
        examples=(
            'heating element failed',
            'heating element failure',
            'broken heating element',
            'heating element open circuit',
            'no power to heating element',
            'heater element fault',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'heating element',
            'heater',
            'boiler',
            'thermal circuit',
            'element',
        ),
    ),
    TextConcept(
        concept_id='limescale_or_scale_build_up',
        label='Limescale or scale build-up',
        kind='diagnosis',
        description='Limescale, limestone, or scale buildup is clogging the machine or triggering descaling needs.',
        examples=(
            'limescale buildup',
            'lime scale build up',
            'clogged with limescale',
            'scale build-up',
            'requires descaling',
            'limestone in machine',
            'Probably lime scale build up',
            'scale light on',
            'small parts of limestone (kalk)',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'limescale',
            'scale',
            'limestone',
            'kalk',
            'boiler',
            'water path',
            'descaling',
        ),
    ),
    TextConcept(
        concept_id='pod_mechanism_or_lid_fault',
        label='Pod mechanism or lid fault',
        kind='diagnosis',
        description='Pod/capsule mechanism, plunger, handle, or lid is loose, broken, or unable to operate correctly.',
        examples=(
            'pod mechanism fault',
            'capsule mechanism fault',
            'pod lid broken',
            'loose machine lid',
            'plunger cannot pierce capsules',
            'broken pod handle',
            "handle/lid' of the machine was loose/nbroken",
            'Plunger not able to pierce capsuls',
            'replaced pod mechanism',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pod mechanism',
            'capsule mechanism',
            'lid',
            'handle',
            'plunger',
            'pod holder',
        ),
    ),
    TextConcept(
        concept_id='pump_fault',
        label='Pump fault',
        kind='diagnosis',
        description='Pump or small pump motor is faulty, seized, dead, or not operating.',
        examples=(
            'pump not working',
            'faulty pump',
            'pump is dead',
            'pump seized',
            'pump motor not operating',
            'water pump fault',
            'Could be faulty pump',
            "Pump doesn't work",
            'small motor not operating',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'pump',
            'water pump',
            'pump motor',
            'small motor',
            'impeller',
        ),
    ),
    TextConcept(
        concept_id='seal_issue',
        label='Seal issue',
        kind='diagnosis',
        description='Seal is dirty, misfitted, worn, or needs replacement, often causing leakage or poor closure.',
        examples=(
            'seal needs replacing',
            'seal needs cleaning',
            'seal not fitting',
            'seal issue',
            'worn seal',
            'bad seal',
            'seal needs cleaning /replaced',
            'Seal not fitting right',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'seal',
            'gasket',
            'o-ring',
            'rubber seal',
            'lid seal',
        ),
    ),
    TextConcept(
        concept_id='switch_or_button_fault',
        label='Switch or button fault',
        kind='diagnosis',
        description='Power switch, tact switch, or button is broken, defective, faulty, or mechanically unreliable.',
        examples=(
            'broken switch',
            'faulty switch',
            'defective switch',
            'broken on switch',
            'tact switch fault',
            'wonky switch',
            'button fault',
            'Switch faulty',
            'Switch broken',
            'Switch is defective',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'switch',
            'button',
            'on switch',
            'power switch',
            'tact switch',
            'control button',
        ),
    ),
    TextConcept(
        concept_id='valve_or_solenoid_fault',
        label='Valve or solenoid fault',
        kind='diagnosis',
        description='Steam valve or solenoid valve is faulty, stripped, or not directing steam correctly.',
        examples=(
            'valve not directing steam',
            'faulty solenoid',
            'solenoid valve fault',
            'steam valve stripped',
            'steam valve fault',
            'valve turns with no effect',
            'Probably one of the solenoids is faulty',
            'Steam valve stripped - turns but no effect',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'valve',
            'steam valve',
            'solenoid',
            'solenoid valve',
            'steam control',
        ),
    ),
    TextConcept(
        concept_id='thermostat_or_rheostat_fault',
        label='Thermostat or rheostat fault',
        kind='diagnosis',
        description='Thermostat or rheostat is suspected faulty or requires replacement in the heating control circuit.',
        examples=(
            'thermostat not working',
            'thermostat fault',
            'replace thermostat',
            'rheostat fault',
            'needs new rheostat',
            'heating control thermostat fault',
            'Changer le thermostat',
            'needs a new rheostat',
        ),
        applicable_service_types=(
            'RepairServiceStep',
            'ReplaceServiceStep',
            'CleaningServiceStep',
            'RefurbishmentServiceStep',
            'RemanufacturingServiceStep',
        ),
        related_part_keywords=(
            'thermostat',
            'rheostat',
            'temperature control',
            'heating control',
            'boiler',
        ),
        inventory_status='review_candidate',
    ),
)


TEXT_CONCEPTS_BY_KIND: dict[TextConceptKind, tuple[TextConcept, ...]] = {
    "symptom": SYMPTOM_CONCEPTS,
    "diagnosis": DIAGNOSIS_CONCEPTS,
}


TEXT_CONCEPTS_BY_ID: dict[str, TextConcept] = {
    concept.concept_id: concept
    for concepts in TEXT_CONCEPTS_BY_KIND.values()
    for concept in concepts
}
