"""
Seeded service concept registry for free-text harmonization.

This module contains domain knowledge only: canonical diagnosis and symptom
concepts, aliases/examples, and optional metadata. Matching logic stays in
free_text.py, so the registry can be reviewed and extended without changing the
normalization algorithm.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


TextConceptKind = Literal["symptom", "diagnosis"]
TextConceptInventoryStatus = Literal["core", "review_candidate"]


@dataclass(frozen=True)
class TextConcept:
    """
    Canonical free-text concept used for service-text harmonization.

    Attributes:
        concept_id: Stable machine-readable identifier.
        label: Human-readable canonical label.
        kind: Concept registry kind, e.g. symptom or diagnosis.
        description: Short semantic description used for embedding matching.
        examples: Seed phrases from the prototype data and dirty variants.
        applicable_service_types: Optional service-step types where the concept is especially plausible.
        related_part_keywords: Optional part-name keywords used for context-aware service checks.
        inventory_status: Whether the concept is part of the ORDS-derived core vocabulary or a review candidate.
    """

    concept_id: str
    label: str
    kind: TextConceptKind
    description: str
    examples: tuple[str, ...] = ()
    applicable_service_types: tuple[str, ...] = ()
    related_part_keywords: tuple[str, ...] = ()
    inventory_status: TextConceptInventoryStatus = "core"


SYMPTOM_CONCEPTS: tuple[TextConcept, ...] = (
    TextConcept(
        concept_id="water_leakage",
        label="Water leakage",
        kind="symptom",
        description="water leaks, dripping after brewing, intermittent dripping, visible leakage around hoses or valves",
        examples=(
            "Water leakage",
            "Dripping after brew",
            "Intermittent dripping",
            "water leak",
            "water leaking",
            "machine leaking",
            "leaking after brew",
            "leaking water",
            "leaks water",
            "liquid escapes around the valve after brewing",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("water_system", "hose", "hoses", "seal", "valve", "solenoid"),
    ),
    TextConcept(
        concept_id="reduced_water_flow_or_low_pressure",
        label="Reduced water flow or low pressure",
        kind="symptom",
        description="weak flow, reduced water output, low brew pressure, pressure fluctuations, or flow oscillation during brewing",
        examples=(
            "Low brew pressure",
            "Pressure fluctuations",
            "Irregular pressure ramp",
            "Flow oscillation",
            "Reduced flow rate",
            "low water flow",
            "weak water flow",
            "low water pressure",
            "reduced water output",
            "not dispensing enough water",
            "pumps slowly",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "CleaningServiceStep"),
        related_part_keywords=("water_system", "pump", "flowmeter", "thermoblock", "solenoid"),
    ),
    TextConcept(
        concept_id="grinder_not_working",
        label="Grinder not working",
        kind="symptom",
        description="grinder does not work, inconsistent grind, abnormal grinding noise, or extraction problems linked to grinding",
        examples=(
            "Watery espresso",
            "Channeling",
            "Inconsistent grind",
            "Increased extraction time variance",
            "Uneven puck surface",
            "Longer extraction",
            "Intermittent grinding noise",
            "Stall on start",
            "Grinding noise at start",
            "grinder not working",
            "not grinding",
            "will not grind",
            "won't grind coffee",
            "stopped grinding coffee",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "CleaningServiceStep"),
        related_part_keywords=("grinder", "burr", "burrs", "motor"),
    ),
    TextConcept(
        concept_id="generic_not_working",
        label="Generic not working",
        kind="symptom",
        description="broad non-specific statement that the coffee machine or item does not work",
        examples=(
            "not working",
            "machine not working",
            "dead",
            "item not working",
            "doesn't work",
            "stopped working",
            "not working at all",
            "nothing happens",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "RefurbishmentServiceStep"),
    ),
    TextConcept(
        concept_id="does_not_turn_on",
        label="Does not turn on",
        kind="symptom",
        description="machine does not switch on or turn on",
        examples=(
            "does not turn on",
            "does not switch on",
            "not turning on",
            "won't turn on",
            "doesn't turn on",
            "not responding to power button",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("electronics", "ui", "pcb", "switch", "button", "fuse"),
    ),
    TextConcept(
        concept_id="no_power_or_no_lights",
        label="No power or no lights",
        kind="symptom",
        description="no electrical power, no lights, or display not powered",
        examples=(
            "no power",
            "no lights",
            "display not powered",
            "no light",
            "no electrical power",
            "light not coming on",
            "no power to display",
            "no lights on panel",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("electronics", "ui", "pcb", "switch", "button", "fuse"),
    ),
    TextConcept(
        concept_id="power_on_but_no_operation",
        label="Power on but no operation",
        kind="symptom",
        description="machine has power or lights but does not operate or respond",
        examples=(
            "Buttons unresponsive",
            "buttons do not respond",
            "button is stuck",
            "powers on but does nothing",
            "power on but not working",
            "lights on but not working",
            "power on but nothing happens",
            "lights on but nothing happens",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("ui", "pcb", "electronics", "button", "display", "switch"),
    ),
    TextConcept(
        concept_id="no_water_flow",
        label="No water flow",
        kind="symptom",
        description="no water or coffee comes through the machine",
        examples=(
            "no water flow",
            "no water coming through",
            "water not coming through",
            "no water or coffee flow",
            "water not going through",
            "water not running through",
            "not percolating",
        ),
        applicable_service_types=("RepairServiceStep", "CleaningServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("water_system", "pump", "hose", "valve", "thermoblock"),
    ),
    TextConcept(
        concept_id="no_coffee_output",
        label="No coffee output",
        kind="symptom",
        description="coffee does not come out or brewing output is missing",
        examples=(
            "no coffee output",
            "coffee not coming through",
            "no coffee",
            "watery espresso",
            "no coffee coming out",
            "coffee not coming out",
            "did not brew",
            "not brewing",
        ),
        applicable_service_types=("RepairServiceStep", "CleaningServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("water_system", "pump", "brew_group", "grinder"),
    ),
    TextConcept(
        concept_id="not_pumping_water",
        label="Not pumping water",
        kind="symptom",
        description="pump appears not to move water or pump priming is abnormal",
        examples=("not pumping water", "pump not pumping", "Noisy pump priming", "water not pumping", "won't pump water"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "CleaningServiceStep"),
        related_part_keywords=("pump", "water_system", "hose"),
    ),
    TextConcept(
        concept_id="water_not_heating",
        label="Water not heating",
        kind="symptom",
        description="water does not heat or machine produces cold coffee",
        examples=(
            "water not heating",
            "does not heat water",
            "cold coffee",
            "not heating",
            "doesn't heat up",
            "not heating water",
            "water not heating up",
            "won't heat water",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("heating", "heater", "thermoblock", "fuse", "thermostat"),
    ),
    TextConcept(
        concept_id="steam_leak",
        label="Steam leak",
        kind="symptom",
        description="steam leaks or escapes from the machine or steam path",
        examples=("steam leak", "leaking steam", "steam escaping", "steam leaking", "steam wand leaking"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("steam", "valve", "seal", "hose", "steam_wand"),
    ),
    TextConcept(
        concept_id="steam_wand_not_working",
        label="Steam wand not working",
        kind="symptom",
        description="steam wand or steam output does not work, is weak, or sputters",
        examples=(
            "steam wand not working",
            "steamer not working",
            "Steam sputtering",
            "machine spits steam",
            "not steaming properly",
            "steam wand losing power",
        ),
        applicable_service_types=("RepairServiceStep", "CleaningServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("steam", "steam_wand", "valve", "nozzle"),
    ),
    TextConcept(
        concept_id="pod_not_pierced",
        label="Pod not pierced",
        kind="symptom",
        description="capsule or pod is not pierced correctly",
        examples=(
            "pod not pierced",
            "capsule not pierced",
            "pod not punctured",
            "pods not pierced",
            "not piercing pods",
            "does not pierce pod",
            "not piercing coffee capsules",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("pod", "capsule", "lid", "piercer"),
    ),
    TextConcept(
        concept_id="pod_jam_or_lid_not_closing",
        label="Pod jam or lid not closing",
        kind="symptom",
        description="pod is jammed or lid cannot close correctly",
        examples=(
            "pod jam",
            "pod jammed",
            "lid not closing",
            "capsule stuck",
            "jammed pods",
            "lid won't close",
            "stuck coffee pod",
            "pod jams",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("pod", "capsule", "lid", "mechanism"),
    ),
    TextConcept(
        concept_id="indicator_light_error",
        label="Indicator light error",
        kind="symptom",
        description="indicator light or status light shows an error",
        examples=("indicator light error", "warning light", "red light flashing"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("ui", "display", "electronics"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="pod_area_leakage",
        label="Pod area leakage",
        kind="symptom",
        description="water leaks from pod or capsule area",
        examples=("leaking from pod area", "pod area leak", "capsule area leaking"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("pod", "capsule", "seal", "lid"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="grinder_not_switching_on",
        label="Grinder not switching on",
        kind="symptom",
        description="grinder specifically does not switch on",
        examples=("grinder not switching on", "grinder does not turn on"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("grinder", "motor", "electronics"),
        inventory_status="review_candidate",
    ),
)


DIAGNOSIS_CONCEPTS: tuple[TextConcept, ...] = (
    TextConcept(
        concept_id="seal_issue",
        label="Seal issue",
        kind="diagnosis",
        description="worn seal, worn valve seal, loose hose clamp, damaged gasket or leak path in water circuit",
        examples=(
            "Seal wear in 3-way valve",
            "rubber gasket no longer seals the water path",
            "worn seal",
            "valve seal wear",
            "seal issue",
            "seal needs replacing",
            "seal not fitting right",
            "seal wear",
            "rubber gasket no longer seals",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("seal", "gasket", "valve", "solenoid", "hose", "hoses", "water_system"),
    ),
    TextConcept(
        concept_id="limescale_or_scale_build_up",
        label="Limescale or scale build-up",
        kind="diagnosis",
        description="lime scale or mineral accumulation in water system, thermoblock, pump or flow path",
        examples=(
            "Lime scale buildup",
            "Limescale accumulation",
            "scale buildup",
            "mineral deposits in water circuit",
            "limescale",
            "lime scale build up",
            "mineral deposits",
            "clogged with limescale",
            "requires descaling",
            "scale light on",
        ),
        applicable_service_types=("CleaningServiceStep", "RepairServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("water_system", "thermoblock", "pump", "flowmeter", "hoses"),
    ),
    TextConcept(
        concept_id="pump_fault",
        label="Pump fault",
        kind="diagnosis",
        description="pump failure or pump fault linked to no-flow or weak-flow symptoms",
        examples=(
            "pump fault",
            "pump is dead",
            "pump failure",
            "pump not working",
            "faulty pump",
            "pump dead",
            "pump seized",
            "small motor not operating",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("pump", "water_system"),
    ),
    TextConcept(
        concept_id="valve_or_solenoid_fault",
        label="Valve or solenoid fault",
        kind="diagnosis",
        description="valve or solenoid fault in the steam or water path",
        examples=(
            "valve fault",
            "solenoid fault",
            "valve_or_solenoid_fault",
            "Check valve fatigue",
            "valve not directing steam",
            "faulty solenoid",
            "steam valve stripped",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("valve", "solenoid", "pump", "water_system", "steam"),
    ),
    TextConcept(
        concept_id="switch_or_button_fault",
        label="Switch or button fault",
        kind="diagnosis",
        description="broken switch, faulty button, stuck button matrix, or UI input fault",
        examples=(
            "Stuck button matrix on UI board",
            "broken switch",
            "faulty switch",
            "button matrix fault",
            "UI board fault",
            "switch faulty",
            "defective switch",
            "tact switch fault",
            "buttons unresponsive",
            "stuck button matrix",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("ui", "pcb", "electronics", "button", "display", "switch"),
    ),
    TextConcept(
        concept_id="dirty_or_corroded_contacts",
        label="Dirty or corroded contacts",
        kind="diagnosis",
        description="dirty or corroded electrical contacts causing switch or input issues",
        examples=(
            "dirty contacts",
            "corroded contacts",
            "dirty or corroded contacts",
            "corroded switch",
            "worn button contact",
            "dirty on/off button",
        ),
        applicable_service_types=("RepairServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("contacts", "electronics", "switch", "button", "pcb"),
    ),
    TextConcept(
        concept_id="fuse_or_thermal_fuse_fault",
        label="Fuse or thermal fuse fault",
        kind="diagnosis",
        description="blown fuse or thermal fuse fault",
        examples=(
            "blown fuse",
            "thermal fuse",
            "fuse fault",
            "blown_or_thermal_fuse",
            "plug fuse blown",
            "thermal fuse blown",
            "need thermal fuse",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("fuse", "thermal", "electronics", "heater"),
    ),
    TextConcept(
        concept_id="heating_element_failure",
        label="Heating element failure",
        kind="diagnosis",
        description="heating element failure or heater fault",
        examples=(
            "heating element failure",
            "heater fault",
            "heating failure",
            "broken heating element",
            "heating element failed",
            "open circuit element",
            "no power to heating element",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("heater", "heating", "thermoblock", "element"),
    ),
    TextConcept(
        concept_id="blocked_steam_nozzle",
        label="Blocked steam nozzle",
        kind="diagnosis",
        description="blocked steam nozzle or steam wand blockage",
        examples=(
            "blocked steam nozzle",
            "blocked nozzle",
            "steam nozzle blocked",
            "steamer nozzle blocked",
            "unblocked nozzle",
            "cleaned steamer nozzle",
        ),
        applicable_service_types=("CleaningServiceStep", "RepairServiceStep"),
        related_part_keywords=("steam", "nozzle", "steam_wand"),
    ),
    TextConcept(
        concept_id="air_in_pump_or_pipe",
        label="Air in pump or pipe",
        kind="diagnosis",
        description="air lock or air in pump/pipe causing flow issues",
        examples=(
            "air in pump",
            "air in pipe",
            "air lock",
            "air_in_pump_or_pipe",
            "pump air",
            "air lock in pump",
            "pump had air in the pipe",
        ),
        applicable_service_types=("RepairServiceStep", "CleaningServiceStep"),
        related_part_keywords=("pump", "pipe", "hose", "water_system"),
    ),
    TextConcept(
        concept_id="blocked_or_disconnected_flow_path",
        label="Blocked or disconnected flow path",
        kind="diagnosis",
        description="blocked or disconnected tubing, hose, or water-flow path",
        examples=(
            "blocked flow path",
            "disconnected pump connection",
            "Loose clamp on silicone hose",
            "plugged tubing",
            "connection came off",
            "loose clamp",
        ),
        applicable_service_types=("RepairServiceStep", "CleaningServiceStep"),
        related_part_keywords=("hose", "hoses", "pipe", "water_system", "pump"),
    ),
    TextConcept(
        concept_id="pod_mechanism_or_lid_fault",
        label="Pod mechanism or lid fault",
        kind="diagnosis",
        description="pod/capsule mechanism, lid, plunger, or piercing fault",
        examples=(
            "pod mechanism fault",
            "lid fault",
            "pod_mechanism_or_lid_fault",
            "lid broken",
            "handle loose",
            "plunger cannot pierce capsules",
            "replaced pod mechanism",
        ),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("pod", "capsule", "lid", "mechanism"),
    ),
    TextConcept(
        concept_id="thermostat_or_rheostat_fault",
        label="Thermostat or rheostat fault",
        kind="diagnosis",
        description="thermostat or rheostat fault linked to heating behavior",
        examples=("thermostat fault", "rheostat fault", "thermostat_or_rheostat_fault"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("thermostat", "rheostat", "heater", "thermoblock"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="dull_burrs",
        label="Dull grinder burrs",
        kind="diagnosis",
        description="grinder burrs are worn or dull and cause inconsistent particle size or extraction quality",
        examples=("Dull burrs", "Dull burrs causing inconsistent grind size", "worn grinder burrs", "grinder blades are no longer sharp"),
        applicable_service_types=("ReplaceServiceStep", "RepairServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("grinder", "burr", "burrs"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="motor_brush_wear",
        label="Motor brush wear",
        kind="diagnosis",
        description="grinder motor brush wear or motor wear causing intermittent start or grinding noise",
        examples=("Motor brush wear", "worn motor brushes"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("grinder", "motor"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="check_valve_fatigue",
        label="Check valve fatigue",
        kind="diagnosis",
        description="check valve fatigue or pump valve problem causing unstable pressure ramp",
        examples=("Check valve fatigue", "pump check valve fatigue"),
        applicable_service_types=("RepairServiceStep", "ReplaceServiceStep"),
        related_part_keywords=("pump", "valve", "water_system"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="loose_hose_or_clamp_issue",
        label="Loose hose or clamp issue",
        kind="diagnosis",
        description="loose hose clamp or hose connection fault causing leakage",
        examples=("Loose clamp on silicone hose", "loose hose clamp"),
        applicable_service_types=("RepairServiceStep",),
        related_part_keywords=("hose", "hoses", "clamp", "water_system"),
        inventory_status="review_candidate",
    ),
    TextConcept(
        concept_id="brew_group_residue_or_friction",
        label="Brew group residue or friction",
        kind="diagnosis",
        description="coffee residue, oil, dirt buildup, or brew group friction causing sticky movement or noise",
        examples=("Residue buildup", "Brew group friction", "coffee residue buildup", "Sticky motion", "Creak noise", "Slower cycle"),
        applicable_service_types=("CleaningServiceStep", "RefurbishmentServiceStep"),
        related_part_keywords=("brew_group", "brew", "piston", "chamber"),
        inventory_status="review_candidate",
    ),
)


TEXT_CONCEPTS_BY_KIND: dict[TextConceptKind, tuple[TextConcept, ...]] = {
    "symptom": SYMPTOM_CONCEPTS,
    "diagnosis": DIAGNOSIS_CONCEPTS,
}


TEXT_CONCEPTS_BY_ID: dict[str, TextConcept] = {
    concept.concept_id: concept
    for concepts in TEXT_CONCEPTS_BY_KIND.values()
    for concept in concepts
}
